# -*- coding: utf-8 -*-
"""Cópia de Aula_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mtaj2StshHcaAr8Q_v7cEaSawUxd1SAP
"""

inteiro = int(input (" Escreve um valor inteiro tio..."))
real = float(input (" Escreve um valor inteiro tio..."))
string = input('Campeao em 2012? ')
resultado = inteiro + real
mensagem = string + "..." + str(resultado)
print(inteiro)
print(real)
print(mensagem, " Receita em milhões")

"""Exemplo numérico"""

a = 20
b = 15

resultado = a*b
print("1) O valor da multiplicação, é esse meu caro...", resultado)

resultado = a**b
print("2) O valor da potencia, é esse meu caro...", resultado)

resultado = a/b
print("3) O valor da divisão, é esse meu caro...", resultado)

resultado = a//b
print("4) O valor da divisão por inteiros, é esse meu caro...", resultado)

resultado = a%b
print("5) O valor percentual, é esse meu caro...", resultado)

"""**# Exercicio 1**

Escreva os programas utilizando a linguagem Python para resolver os problemas a seguir:

Ler 4 valores, calcular a média entre eles e apresentar o resultado.


"""

x1 = 5.4
x2 = 5
x3 = 5
x4 = 10

resultado_media=(x1 + x2+ x3+ x4)/4

print(" A média da resultado é essa meu filho", resultado_media)

"""**# Exercicio 2**

Ler o nome de um produto, o seu valor e a quantidade comprada e apresentar uma mensagem contendo o nome do produto, o seu valor unitário e o valor total da compra.
"""

produto = "Caneca_Corinthians"
preco = 500.89
quantidade = 10

resultado = float(preco*quantidade)

print("O nome do produto é...", produto)

print("O preço do produto é...", preco)

print("A quantidade do produto é...", quantidade)


print("O valor total da sua compra é...", resultado)