# -*- coding: utf-8 -*-
"""Aitividade_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1toc_bqfodsO-dGhNDrj_cR043-A3hsm1

**Atividade 5**

**Exercício 1** – Altere o programa feito nas aulas passadas e adicione uma estrutura de repetição que permita ao usuário informar o nome de 10 disciplinas.

Enunciado da aula anterior: Para ser aprovado em uma disciplina o aluno precisa obter média final maior ou igual a 7,00. Considere que em uma determinada disciplina ele realiza 3 atividades com os seguintes pesos: Prova – peso 45%, Projeto – peso 25%, Atividades – peso 30%. Caso o aluno não alcance a média 
7,0 ele poderá realizar uma prova chamada EXAME. O novo resultado deverá ser calculado com a média simples entre a média anterior e a nota do exame. Altere o programa anterior adicionando uma condição para verificar situação do aluno: Aprovado, Aprovado com exame ou Reprovado e a respectiva média.
"""

i = 1
while i < 11:
  i=i+1
  disciplina = input('Digite o nome de sua disciplina ')
  prova = float(input(" Digite a nota da prova "))
  projeto = float(input(" Digite a nota do projeto "))
  atividade = float(input(" Digite a nota da atividade "))

  peso_1 = prova*0.45
  peso_2 = projeto*0.25
  peso_3 = atividade*0.30

  nota_final= peso_1 + peso_2 + peso_3

  if nota_final >= 7.00:
    print('Aluno aprovado')
  elif nota_final <7:
    print('O Aluno/a precisa realizar uma nova prova')
    nova_prova= float(input(" Digite a nota da nova prova de 0 a 10 "))
    nova_media = float(nota_final + nova_prova)/2
    print('A nova media é ', nova_media)

  if nova_media >=7:
    print("Logo, aluno/a aprovado")
  else:
    print('Logo, aluno/a reprovado')

"""'''**Exercício 2** – Permita que o usuário informe o nome de 10 pessoas (uma a uma)  e os seus dados para calcular o seu IMC conforme especificações apresentadas abaixo: """

# nomes, pesos e alturas

contador = 1
while contador <11:
  contador = contador + 1
  nome_pessoas = input("Dgite o nome da pessoa ")
  peso = float(input(' Qual o peso dessa pessoa em Kg '))
  altura= float(input('Qual a altura dessa pessoa em metros '))
  imc = peso*(altura**2)
  print("o IMC da pessoa é ", imc)

  if imc < 18.5:
    print(" Está abaixo do peso ")
  elif imc <= 18.5 and imc < 25:
    print(" Está saudável ")
  elif imc <= 25 and imc < 30:
    print(" Está com sobrepeso ")
  elif imc <= 30 and imc < 35:
    print(" Está com nível de obesidade em grau I ")
  elif imc <= 35 and imc < 40:
    print(" Está com nível de obesidade em grau II, considerada severa ") 
  else:
    print(" Está com nível de obesidade em grau III, considerada mórbida ")

"""'''**Exercício 3** – Altere o programa anterior para que o usuário determine quando deseja encerrar o laço de repetição.'''"""

# nomes, pesos e alturas


# informar o numero de pessoas para ele escolher qts quer e encerrar o laco.
encerramento_laco = int(input(' Informe quantas pessoas deseja calcular o IMC? '))

contador = 0
while contador < encerramento_laco:
  contador = contador + 1
  nome_pessoas = input("Dgite o nome da pessoa ")
  peso = float(input(' Qual o peso dessa pessoa em Kg '))
  altura= float(input('Qual a altura dessa pessoa em metros '))
  imc = peso*(altura**2)
  print("o IMC da pessoa é ", imc)

  if imc < 18.5:
    print(" Está abaixo do peso ")
  elif imc <= 18.5 and imc < 25:
    print(" Está saudável ")
  elif imc <= 25 and imc < 30:
    print(" Está com sobrepeso ")
  elif imc <= 30 and imc < 35:
    print(" Está com nível de obesidade em grau I ")
  elif imc <= 35 and imc < 40:
    print(" Está com nível de obesidade em grau II, considerada severa ") 
  else:
    print(" Está com nível de obesidade em grau III, considerada mórbida ")

"""'''**Exercício 4** – Desafio: Altere o programa anterior e quando o usuário desejar encerra o programa mostre a quantidade de pessoas e a média de peso do grupo.'''"""

# informar o numero de pessoas para ele escolher qts quer e encerrar o laco.
encerramento_laco = int(input(' Informe quantas pessoas deseja calcular o IMC? '))

soma_peso= 0
contador = 0
while contador < encerramento_laco:
  contador = contador + 1


  nome_pessoas = input("Dgite o nome da pessoa ")
  peso = float(input(' Qual o peso dessa pessoa em Kg '))
  altura= float(input('Qual a altura dessa pessoa em metros '))
  imc = peso*(altura**2)
  print("o IMC da pessoa é ", imc)
  soma_peso = soma_peso + peso

  if imc < 18.5:
    print(" Está abaixo do peso ")
  elif imc <= 18.5 and imc < 25:
    print(" Está saudável ")
  elif imc <= 25 and imc < 30:
    print(" Está com sobrepeso ")
  elif imc <= 30 and imc < 35:
    print(" Está com nível de obesidade em grau I ")
  elif imc <= 35 and imc < 40:
    print(" Está com nível de obesidade em grau II, considerada severa ") 
  else:
    print(" Está com nível de obesidade em grau III, considerada mórbida ") 

media =  soma_peso / encerramento_laco

print(' o numero de pessoas foi  ', contador)
print(' A média do peso do numero de pessoas é  ', media)